insert into public.vehicles (id,name,brand,model,year,mileage,transmission,fuel,body,colour,engine,power,condition,price,installment,description,features,images,vin,stock,status,featured,sold,reserved,archived,sort_order,created_at,updated_at) values
  ('v_site_1','Audi A3','Audi','A3',2015,81730,'Manual','Petrol','Sedan','','1.8L','132 kW','Excellent',279900,4665,'Introducing the stylish Audi A3 Sedan 1.8 TFSI SE, a vibrant red beauty that''s perfect for those who love a mix of fun and practicality. With a sleek body and a punchy 132kW petrol engine, this car offers an exhilarating drive with a top speed of 242 km/h. Its manual transmission ensures you stay connected to the road, while features like cruise control and electric windows add to the driving comfort. Safety is prioritised with seven airbags and ABS as standard, providing peace of mind on every journey. The full service record guarantees reliable performance, complemented by LED and Xenon lights that light up the night. The sunroof invites the outdoors in, making every trip a special occasion.','[]'::jsonb,'["https://supremeautonorth.co.za/assets/images/inventory/audi-a3/1.jpg", "https://supremeautonorth.co.za/assets/images/inventory/audi-a3/2.jpg", "https://supremeautonorth.co.za/assets/images/inventory/audi-a3/3.jpg", "https://supremeautonorth.co.za/assets/images/inventory/audi-a3/4.jpg", "https://supremeautonorth.co.za/assets/images/inventory/audi-a3/5.jpg"]'::jsonb,'','11037962','available',false,false,false,false,0,now(),now()),
  ('v_site_2','BMW 3 Series 320i M Sport','BMW','3 Series 320i M Sport',2014,186600,'Automatic','Petrol','Sedan','','2.0L','','Excellent',189900,3165,'A striking blue 2014 BMW 320i M Sport Auto, finished in good condition with the M Sport package. Five-seat, 4x2 layout with petrol engine and automatic transmission for an easy, confident drive.','[]'::jsonb,'["https://supremeautonorth.co.za/assets/images/inventory/bmw-320-i/1.jpg", "https://supremeautonorth.co.za/assets/images/inventory/bmw-320-i/2.jpg", "https://supremeautonorth.co.za/assets/images/inventory/bmw-320-i/3.jpg", "https://supremeautonorth.co.za/assets/images/inventory/bmw-320-i/4.jpg", "https://supremeautonorth.co.za/assets/images/inventory/bmw-320-i/5.jpg"]'::jsonb,'','11061573','available',false,false,false,false,1,now(),now()),
  ('v_site_3','Hyundai Creta 1.5D Executive','Hyundai','Creta 1.5D Executive',2021,92650,'Automatic','Diesel','SUV','','1.5L','','Excellent',259900,4330,'A 2021 Hyundai Creta 1.5D Executive Auto in excellent condition, finished in red. Diesel automatic, five-seat SUV layout with the practicality and efficiency the Creta is known for.','[]'::jsonb,'["https://supremeautonorth.co.za/assets/images/inventory/hyundai-creta/1.jpg", "https://supremeautonorth.co.za/assets/images/inventory/hyundai-creta/2.jpg", "https://supremeautonorth.co.za/assets/images/inventory/hyundai-creta/3.jpg", "https://supremeautonorth.co.za/assets/images/inventory/hyundai-creta/4.jpg", "https://supremeautonorth.co.za/assets/images/inventory/hyundai-creta/5.jpg"]'::jsonb,'','','available',false,false,false,false,2,now(),now()),
  ('v_site_4','Hyundai H-1','Hyundai','H-1',2018,197320,'Automatic','Diesel','MPV','','2.5L','125 kW','Excellent',319900,5330,'This stylish white vehicle combines practicality with comfort, featuring leather seats and a suite of modern options including electric windows, air conditioning, cruise control, and park distance control to make every journey smooth and enjoyable. Equipped with a reliable automatic transmission and a robust 125kW diesel engine, it offers a maximum speed of 180 km/h and a fuel efficiency averaging 9.8 litres per 100 km. Safety is a priority with four airbags, ABS as standard, and an alarm system to keep you secure.','[]'::jsonb,'["https://supremeautonorth.co.za/assets/images/inventory/hyundai-h1/1.jpg", "https://supremeautonorth.co.za/assets/images/inventory/hyundai-h1/2.jpg", "https://supremeautonorth.co.za/assets/images/inventory/hyundai-h1/3.jpg", "https://supremeautonorth.co.za/assets/images/inventory/hyundai-h1/4.jpg", "https://supremeautonorth.co.za/assets/images/inventory/hyundai-h1/5.jpg"]'::jsonb,'','11045279','available',false,false,false,false,3,now(),now()),
  ('v_site_5','Kia Sportage 2.0 Ignite','Kia','Sportage 2.0 Ignite',2018,133297,'Manual','Petrol','SUV','','2.0L','','Excellent',199900,3330,'A 2018 Kia Sportage 2.0 Ignite Manual Petrol in excellent condition, finished in white. Five-seat, 4x2 SUV layout -- practical, well-kept family transport.','[]'::jsonb,'["https://supremeautonorth.co.za/assets/images/inventory/kia-sportage/1.jpg", "https://supremeautonorth.co.za/assets/images/inventory/kia-sportage/2.jpg", "https://supremeautonorth.co.za/assets/images/inventory/kia-sportage/3.jpg", "https://supremeautonorth.co.za/assets/images/inventory/kia-sportage/4.jpg", "https://supremeautonorth.co.za/assets/images/inventory/kia-sportage/5.jpg"]'::jsonb,'','','available',false,false,false,false,4,now(),now()),
  ('v_site_6','Nissan X-Trail 1.6 dCi XE','Nissan','X-Trail 1.6 dCi XE',2015,164625,'Manual','Diesel','SUV','','1.6L','','Excellent',169900,2830,'A 2015 Nissan X-Trail 1.6 dCi XE 5-Seater in excellent condition, finished in silver. Diesel manual, 4x2 -- a dependable family SUV.','[]'::jsonb,'["https://supremeautonorth.co.za/assets/images/inventory/nissan-x-trail/1.jpg", "https://supremeautonorth.co.za/assets/images/inventory/nissan-x-trail/2.jpg", "https://supremeautonorth.co.za/assets/images/inventory/nissan-x-trail/3.jpg", "https://supremeautonorth.co.za/assets/images/inventory/nissan-x-trail/4.jpg", "https://supremeautonorth.co.za/assets/images/inventory/nissan-x-trail/5.jpg"]'::jsonb,'','9027593','available',false,false,false,false,5,now(),now()),
  ('v_site_7','Renault Duster','Renault','Duster',2019,83660,'Automatic','Diesel','Crossover','','1.5L','80 kW','Excellent',209900,3500,'Discover the stylish and reliable Renault Duster 1.5 dCi Prestige Auto in a striking blue finish, perfect for urban adventures or countryside escapes. With a modest 83,660 km on the clock, this excellent condition crossover combines practicality with flair. Its automatic dual-clutch transmission ensures smooth driving, while the 80kW diesel engine delivers an impressive fuel range of approximately 1042 km and fuel efficiency of just 4.8 L/100 km. The Duster is packed with features including four airbags, ABS, LED lights, rear-view camera, air conditioning, and a sophisticated alarm system for added safety and comfort. Enjoy luxe leather seats and the convenience of electric windows, park distance control, cruise control, and a quality radio to keep you entertained.','[]'::jsonb,'["https://supremeautonorth.co.za/assets/images/inventory/renault-duster/1.jpg", "https://supremeautonorth.co.za/assets/images/inventory/renault-duster/2.jpg", "https://supremeautonorth.co.za/assets/images/inventory/renault-duster/3.jpg", "https://supremeautonorth.co.za/assets/images/inventory/renault-duster/4.jpg", "https://supremeautonorth.co.za/assets/images/inventory/renault-duster/5.jpg"]'::jsonb,'','10971409','available',false,false,false,false,6,now(),now()),
  ('v_site_8','Volkswagen Polo 1.0 TSI Comfortline','Volkswagen','Polo 1.0 TSI Comfortline',2019,174270,'Manual','Petrol','Hatch','','1.0L','','Excellent',219900,3665,'A 2019 Volkswagen Polo 1.0 TSI Comfortline Manual in good condition, finished in gold. Five-seat, 4x2 hatchback layout with petrol engine and manual transmission.','[]'::jsonb,'["https://supremeautonorth.co.za/assets/images/inventory/volkswagen-polo/1.jpg", "https://supremeautonorth.co.za/assets/images/inventory/volkswagen-polo/2.jpg", "https://supremeautonorth.co.za/assets/images/inventory/volkswagen-polo/3.jpg", "https://supremeautonorth.co.za/assets/images/inventory/volkswagen-polo/4.jpg", "https://supremeautonorth.co.za/assets/images/inventory/volkswagen-polo/5.jpg"]'::jsonb,'','','available',false,false,false,false,7,now(),now()),
  ('v_site_9','Volkswagen Polo GTI','Volkswagen','Polo GTI',2016,100230,'Automatic','Petrol','Hatch','','1.8L','141 kW','Excellent',269900,4498,'A 2016 Volkswagen Polo GTI Auto -- the 1.8 TSI hot hatch with 141kW on tap, 0-100 km/h in 6.7s, and fuel consumption of 5.6L/100km. Five-seat layout, automatic transmission, finished in blue with the GTI''s signature red detailing.','[]'::jsonb,'["https://supremeautonorth.co.za/assets/images/inventory/volkswagen-polo-gti/1.jpg", "https://supremeautonorth.co.za/assets/images/inventory/volkswagen-polo-gti/2.jpg", "https://supremeautonorth.co.za/assets/images/inventory/volkswagen-polo-gti/3.jpg", "https://supremeautonorth.co.za/assets/images/inventory/volkswagen-polo-gti/4.jpg", "https://supremeautonorth.co.za/assets/images/inventory/volkswagen-polo-gti/5.jpg"]'::jsonb,'','','available',false,false,false,false,8,now(),now()),
  ('v_site_10','Volkswagen T-Cross 1.0 TSI Comfortline','Volkswagen','T-Cross 1.0 TSI Comfortline',2021,78170,'Automatic','Petrol','Crossover','','1.0L','','Excellent',259900,4634,'A 2021 Volkswagen T-Cross 1.0 TSI Comfortline Auto in good condition with low mileage, finished in green. Petrol automatic, 4x2 crossover layout.','[]'::jsonb,'["https://supremeautonorth.co.za/assets/images/inventory/volkswagen-t-cross/1.jpg", "https://supremeautonorth.co.za/assets/images/inventory/volkswagen-t-cross/2.jpg", "https://supremeautonorth.co.za/assets/images/inventory/volkswagen-t-cross/3.jpg", "https://supremeautonorth.co.za/assets/images/inventory/volkswagen-t-cross/4.jpg", "https://supremeautonorth.co.za/assets/images/inventory/volkswagen-t-cross/5.jpg"]'::jsonb,'','10901309','available',false,false,false,false,9,now(),now())
on conflict (id) do update set
  name=excluded.name, brand=excluded.brand, model=excluded.model, year=excluded.year,
  mileage=excluded.mileage, transmission=excluded.transmission, fuel=excluded.fuel,
  body=excluded.body, engine=excluded.engine, power=excluded.power, price=excluded.price,
  installment=excluded.installment, description=excluded.description,
  images=excluded.images, stock=excluded.stock, sort_order=excluded.sort_order,
  updated_at=now();

alter table public.testimonials add column if not exists source text not null default 'Direct';

insert into public.testimonials (id,name,vehicle,rating,review,photo,featured,source,created_at,updated_at) values
  ('t_google_1','Pieter Vanheerden','',5,'Staff is exactly helpful and they have a excellent range of cars in stock .','',true,'Google',now(),now()),
  ('t_google_2','Hardus Nepgen','',5,'Get your car at them and u get a nice drive','',true,'Google',now(),now()),
  ('t_google_3','Roberto Mc Kay','',5,'','',true,'Google',now(),now()),
  ('t_google_4','nkululeko malatjie','',5,'Brilliant','',true,'Google',now(),now()),
  ('t_google_5','Sanele Buthelezi','',5,'These guys are amazing and very professional. I got a VW Polo GTI manual from them in March 2026. I want to send a special thanks and rate them 5/5 for the service received from John, Des and Chris. The vehicle is a dream and I have zero complaints.','',true,'Google',now(),now()),
  ('t_google_6','Aurilo Matjan','',5,'I can say with all honesty that dealing with Supreme Auto 1 has been an extreme joy, beyond what I expected. Buying a vehicle in Gauteng and courier the vehicle to Cape Town was a big concern but the help of the Supreme Auto 1 team has made my purchasing journey very easy and to my satisfaction. The salesperson John and F&I Des, from the first message, kept me updated, if I had questions he would respond immediately, constantly sending me updates, very friendly, professional & what he promised I got. Thank you keep it up!','',true,'Google',now(),now()),
  ('t_google_7','Giuseppe Rivoli','',5,'Bought a car recently from Gavin and Johnathan,,, excellent service received.. Highly recommend,,,they did all what they promised and more. Thanks','',true,'Google',now(),now()),
  ('t_google_8','cleaning specialist','',5,'Well I bought a Mahindra single cab from the lady and guy. That works there. I arrived early Saturday morning. While I waited for my wife to fill the paperwork. They did a full service. Oil filters everything. When I saw the car it looked exactly like the pictures. They told me all the things relating to the bakkie that I asked. I am very happy. The car was as promised. Not perfect but close. I am very impressed they charged me what they asked no hidden costs nothing. Thank you. The staff were really accommodation and friendly. Thanks again.','',true,'Google',now(),now())
on conflict (id) do update set
  name=excluded.name, rating=excluded.rating, review=excluded.review,
  source=excluded.source, updated_at=now();

insert into public.site_settings (key,value) values
  ('homepage','{"heroTitle": "Premium Vehicles. Trusted People. Exceptional Value.", "heroSubtitle": "Carefully inspected vehicles, transparent pricing and flexible finance solutions from a dealership committed to earning your trust before making a sale.", "heroBadge": "Premium vehicles · Pretoria North", "btn1Text": "Browse Inventory", "btn1Link": "#inventory", "btn2Text": "Contact Us", "btn2Link": "#contact", "stats": [{"label": "Vehicles Sold", "value": "5000+"}, {"label": "Financing Partners", "value": "5"}], "aboutTitle": "About Supreme Auto", "aboutText": "We''re an independent premium dealership in Pretoria North. Every vehicle on our floor is hand-picked and carefully inspected, because the reputation we''ve built matters more to us than any single sale."}'::jsonb),
  ('contact','{"phone": "(082) 771-8514", "whatsapp": "+27 76 861 5477", "email": "supremea1auto@gmail.com", "address": "546 Rachel de Beer St, Pretoria North, Pretoria", "mapsUrl": "https://maps.google.com/?q=546+Rachel+de+Beer+St+Pretoria+North", "hours": [{"day": "Monday", "open": "08:00", "close": "17:00", "closed": false}, {"day": "Tuesday", "open": "08:00", "close": "17:00", "closed": false}, {"day": "Wednesday", "open": "08:00", "close": "17:00", "closed": false}, {"day": "Thursday", "open": "08:00", "close": "17:00", "closed": false}, {"day": "Friday", "open": "08:00", "close": "17:00", "closed": false}, {"day": "Saturday", "open": "08:00", "close": "13:00", "closed": false}, {"day": "Sunday", "open": "", "close": "", "closed": true}], "social": {"facebook": "https://www.facebook.com/PretoriaSupremeAuto", "instagram": "https://www.instagram.com/pretoriasupremeauto/", "tiktok": "https://www.tiktok.com/@supremeautoa1", "youtube": "", "x": ""}}'::jsonb)
on conflict (key) do update set value=excluded.value, updated_at=now();
